
image: gitpod/workspace-full:latest

tasks:
  - name: Dev Server
    before: | 
      curl -fsSL https://bun.sh/install | bash
      source ~/.bashrc
    init: bun install
    command: bun run dev

vscode:
  extensions:
		- eamodio.gitlens
    - antfu.unocss
    - astro-build.astro-vscode
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - svelte.svelte-vscode
    - unifiedjs.vscode-mdx
    - ZixuanChen.vitest-explorer
